//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABC_Analysis_presenter
{
    using System;
    using System.Collections.Generic;
    
    public partial class Opro
    {
        public int ID_opros { get; set; }
        public int Otcsenka { get; set; }
        public int Nomer_tura { get; set; }
        public string Napravlenie { get; set; }
        public int ID_sotrudnika { get; set; }
        public int ID_napravlenia { get; set; }
        public int ID_rezultat_oprosa { get; set; }
    
        public virtual Napravlenie Napravlenie1 { get; set; }
        public virtual Rezultat_oprosa Rezultat_oprosa { get; set; }
        public virtual Sotrudniki Sotrudniki { get; set; }
    }
}
